### ISSUE TITLE
docker: figure out a way to initialize `data/` on container creation

### ISSUE THREAD

**Issue by RalphORama** [podaboutlist/rss2jext#1]
Currently, running the container with `docker compose` results in a file not found error:

```yml
# docker-compose.yml
services:
  rss2jext:
    image: ghcr.io/podaboutlist/rss2jext:latest
    environment:
      # <snip>
    volumes:
      - type: bind
        source: ./data
        target: /app/data

volumes:
  data:
```

```
$ docker compose up
[+] Running 2/2
 ✔ Volume "rss2jext_data"         Created                                                                          0.1s
 ✔ Container rss2jext-rss2jext-1  Recreated                                                                        0.6s
Attaching to rss2jext-rss2jext-1
rss2jext-rss2jext-1  | Traceback (most recent call last):
rss2jext-rss2jext-1  |   File "/app/src/rss2jext.py", line 176, in <module>
rss2jext-rss2jext-1  |     main()
rss2jext-rss2jext-1  |   File "/app/src/rss2jext.py", line 126, in main
rss2jext-rss2jext-1  |     ptero_servers = load_servers()
rss2jext-rss2jext-1  |                     ^^^^^^^^^^^^^^
rss2jext-rss2jext-1  |   File "/app/src/rss2jext.py", line 25, in load_servers
rss2jext-rss2jext-1  |     with open(
rss2jext-rss2jext-1  |          ^^^^^
rss2jext-rss2jext-1  | FileNotFoundError: [Errno 2] No such file or directory: '/app/data/servers.json'
rss2jext-rss2jext-1 exited with code 1
```
